foreground              #FFFFFF
background              #0F4477
selection_foreground    #0F4477
selection_background    #FFFFFF
cursor                  #CAAD8E 
cursor_text_color       #0D0D0E

active_tab_foreground     #0F4477
active_tab_background     #4A728D
inactive_tab_foreground   #4A728D
inactive_tab_background   #0F4477

# black
color0      #293E52
color8      #57738F

# red
color1      #FFE6CC
color9      #F0CEAA

# green
color2      #CCEDFF
color10     #AAD7F0

# yellow
color3      #CCEAFF
color11     #AAD4F0

# blue
color4      #9AC0E6
color12     #9AC0E6

# magenta
color5      #9ACAE6
color13     #9ACAE6

# cyan
color6      #9AC7E6
color14     #9AC7E6

# white
color7      #FFE6CC
color15     #F0CEAA
