set -g default-terminal "screen-256color"
set -g mouse on

# set new prefix to space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# rebind splits
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# refresh tmux config
unbind r
bind r source-file ~/.tmux.conf

# resizing panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# shift + alt + h
bind -n M-H previous-window 
bind -n M-L next-window

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectange-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run '~/.tmux/plugins/tpm/tpm'

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
