general {
    col.active_border = rgba(CAAD8Eff) rgba(523E29ff) 45deg
    col.inactive_border = rgba(0F4477ff) rgba(4986A8ff) 45deg
}

group {
    col.border_active = rgba(CAAD8Eff) rgba(523E29ff) 45deg
    col.border_inactive = rgba(0F4477cc) rgba(4986A8cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(0D0D0Eff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FDFDFDcc) 45deg
}
