import = [
    "~/.config/alacritty/themes/catppuccin.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "OnlyLeft"
#opacity = 0.69

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 20
