######### OPTIONS / KEYBINDS ##########
set -g default-terminal "screen-256color"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Rebind splits
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
unbind c
bind c new-window -c "#{pane_current_path}"

# Source tmux config
unbind r
bind r source-file ~/.tmux.conf

# Pane sizing up and down
bind -r d resize-pane -D 5
bind -r u resize-pane -U 5

# Make current pane full screen
bind -r m resize-pane -Z

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set vi-mode
set-window-option -g mode-keys vi

# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

######### PLUGINS ##########
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

########## THEME ###########
bg="#1e1e2e"
fg="#dadae8"
cyan="#c2e7f0"
black="#15121c"
gray="#332e41"
magenta="#c6aae8"
pink="#e5b4e2"
red="#e38c8f"
green="#b1e3ad"
yellow="#ebddaa"
blue="#a4b9ef"
orange="#f9c096"
black4="#575268"

######## STATUS BAR ########

# General
set -g status-position top  
set -g status "on"
set -g status-bg "${bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style fg="${cyan}",bg="${gray}",align="centre"
set -g message-command-style fg="${cyan}",bg="${gray}",align="centre"

# Panes
set -g pane-border-style fg="${gray}"
set -g pane-active-border-style fg="${blue}"

# Windows
setw -g window-status-activity-style fg="${fg}",bg="${bg}",none
setw -g window-status-separator ""
setw -g window-status-style fg="${fg}",bg="${bg}",none

# Status bar
set -g status-left ""
set -g status-right "#[fg=$green,bg=$bg,nobold,nounderscore,noitalics]#[fg=$bg,bg=$green,nobold,nounderscore,noitalics] #[fg=$fg,bg=$gray] #W #{?client_prefix,#[fg=$red],#[fg=$magenta]}#[bg=$gray]#{?client_prefix,#[bg=$red],#[bg=$magenta]}#[fg=$bg] #[fg=$fg,bg=$gray] #S "

# Current directory
setw -g window-status-format "#[fg=$bg,bg=$blue] #I #[fg=$fg,bg=$gray] #W "

# Parent directory
setw -g window-status-current-format "#[fg=colour232,bg=$orange] #I #[fg=colour255,bg=colour237] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "

# Clock mode
setw -g clock-mode-colour "${blue}"
setw -g mode-style "fg=${pink} bg=${black4} bold"

